version: "3.9"

services:
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host=0.0.0.0"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ../data:/data
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
