mqtt:
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  user: frigate
  password: '#Frigate7214'

# Basic detector configuration
detectors:
  cpu1:
    type: cpu
    num_threads: 3

# Minimal camera configuration for testing
cameras:
  test_camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:%23Dakman7214@192.168.1.112:554/h264Preview_01_main
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true

# Basic logging
logger:
  default: info
  logs:
    frigate.mqtt: error
    frigate.app: info

version: 0.15 

record:
  enabled: true
  retain:
    days: 7
    mode: motion 