mqtt:
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  user: frigate
  password: '#Frigate7214'

# go2rtc configuration for live streaming with hardware acceleration
go2rtc:
  ffmpeg:
    # Optimized NVIDIA NVENC preset - reduced memory usage
    nvenc: -hwaccel cuda -hwaccel_output_format cuda -c:v h264_nvenc -preset p4 -tune ll -rc cbr -b:v 500k -maxrate 800k -bufsize 400k -g 30 -bf 0
    # Audio transcoding for iOS compatibility  
    audio: -c:a aac -b:a 64k -ar 44100 -ac 2
    # Simplified MP4 streaming - reduced GPU memory usage
    mp4: -hwaccel cuda -c:v h264_nvenc -preset p4 -profile:v baseline -level 3.1 -pix_fmt yuv420p -vf scale_cuda=960:540 -b:v 400k -maxrate 600k -bufsize 300k -g 30 -c:a aac -b:a 64k -ar 44100 -ac 2

  streams:
    # Source streams (defined first)
    Frontyard_main:
      - rtsp://Dakota:%23Dakman7214@192.168.1.112:554/h265Preview_01_main
    Frontyard_sub:
      - rtsp://Dakota:%23Dakman7214@192.168.1.112:554/h264Preview_01_sub
    Backyard_main:
      - rtsp://Dakota:%23Dakman7214@192.168.1.113:554/h265Preview_01_main
    Backyard_sub:
      - rtsp://Dakota:%23Dakman7214@192.168.1.113:554/h264Preview_01_sub

    # Indoor cameras (H.264 streams)
    Living_Room:
      - rtsp://Dakota:%23Dakman7214@192.168.1.114:554/h264Preview_01_main
    Nursery:
      - rtsp://Dakota:%23Dakman7214@192.168.1.115:554/h264Preview_01_main

    # Optimized live streams - only when needed, reduced transcoding
    Frontyard_live:
      - ffmpeg:Frontyard_sub#video=copy#audio=audio  # Copy video, transcode audio only
    Backyard_live:
      - ffmpeg:Backyard_sub#video=copy#audio=audio   # Copy video, transcode audio only
    Living_Room_live:
      - ffmpeg:Living_Room#video=copy#audio=audio    # Copy video, transcode audio only
    Nursery_live:
      - ffmpeg:Nursery#video=copy#audio=audio        # Copy video, transcode audio only

  # API configuration
  api:
    listen: :1984
    cors: ['*']

  # Log configuration - reduced verbosity to save CPU
  log:
    level: info  # Reduced from debug
    format: text

  # WebRTC configuration with direct connection only (no TURN) - COMMENTED OUT
  # webrtc:
  #   listen: "127.0.0.1:8555"
  #   ice_servers:
  #     - urls: [stun:stun.l.google.com:19302]

  # Optimize for on-demand streaming - force MP4 for all devices including iOS
  rtsp:
    default_query: mp4    # Prefer MP4 container for browser compatibility


# Detector configuration - TensorRT (stable)
detectors:
  tensorrt:
    type: tensorrt
    device: 0

# Model configuration - Working YOLOv7-320 with optimizations
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nhwc
  input_pixel_format: rgb
  width: 320
  height: 320

# Recording configuration - Continuous recording for all cameras
record:
  enabled: true
  retain:
    days: 7
    mode: all

# Snapshots configuration
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

# FFmpeg configuration with optimized hardware acceleration
ffmpeg:
  # Hardware acceleration for NVIDIA with optimized settings
  hwaccel_args: preset-nvidia-h264
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -timeout
    - '5000000'  # Fixed: was -stimeout, now -timeout
    # Optimized NVIDIA decoding - reduce GPU memory usage
    - -hwaccel
    - cuda
    - -hwaccel_output_format
    - cuda
    - -extra_hw_frames
    - '2'  # Reduced from 8 to save GPU memory

# Camera configurations
cameras:
  Frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/Frontyard_sub
          roles: [detect]
          input_args:
            - -r
            - '10'
        - path: rtsp://localhost:8554/Frontyard_main
          roles: [record]
    live:
      stream_name: Frontyard_live  # Uses hardware-accelerated on-demand stream
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 10
    motion:
      threshold: 15
      contour_area: 15
      delta_alpha: 0.4
      frame_alpha: 0.01
      improve_contrast: true
      mask: 0.354,0.022,0.64,0.022,0.638,0.07,0.352,0.071
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - car
        - truck
        - motorcycle
        - bicycle
        - bus
      filters:
        person:
          min_area: 200  # Increased from 150 to filter out small false positives
          max_area: 100000
          threshold: 0.5  # Increased from 0.4 to reduce false positives
        car:
          min_area: 2000  # Increased from 1000 for better filtering
          max_area: 100000
          threshold: 0.6  # Reduced from 0.7 to catch more cars
          # mask: 
          #   0.426,0.376,0.485,0.353,0.535,0.309,0.598,0.299,0.649,0.309,0.695,0.327,0.724,0.383,0.735,0.429,0.724,0.509,0.692,0.55,0.669,0.55,0.63,0.524,0.537,0.535,0.521,0.563,0.476,0.572,0.444,0.55,0.402,0.501,0.389,0.451,0.401,0.398
        truck:
          min_area: 1000
          max_area: 100000
          threshold: 0.6
        motorcycle:
          min_area: 300
          max_area: 100000
          threshold: 0.6
        bicycle:
          min_area: 300
          max_area: 100000
          threshold: 0.6
        bus:
          min_area: 2000
          max_area: 100000
          threshold: 0.6

  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/Backyard_sub
          roles: [detect]
          input_args:
            - -r
            - '10'
        - path: rtsp://localhost:8554/Backyard_main
          roles: [record]
    live:
      stream_name: Backyard_live  # Uses hardware-accelerated on-demand stream
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 10
    motion:
      threshold: 15
      contour_area: 15
      delta_alpha: 0.4
      frame_alpha: 0.01
      improve_contrast: true
      mask: 0.355,0.023,0.642,0.024,0.643,0.063,0.643,0.063,0.353,0.072
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - car
        - truck
        - motorcycle
        - bicycle
        - bus
      filters:
        person:
          min_area: 200  # Increased from 150 to filter out small false positives
          max_area: 100000
          threshold: 0.5  # Increased from 0.4 to reduce false positives
        car:
          min_area: 2000  # Increased from 1000 for better filtering
          max_area: 100000
          threshold: 0.6  # Reduced from 0.7 to catch more cars
          # mask: 
          #   0.443,0.45,0.463,0.412,0.495,0.403,0.493,0.329,0.557,0.309,0.608,0.302,0.615,0.374,0.599,0.412,0.583,0.461,0.58,0.5,0.542,0.496,0.485,0.503,0.451,0.491
        truck:
          min_area: 1000
          max_area: 100000
          threshold: 0.6
        motorcycle:
          min_area: 300
          max_area: 100000
          threshold: 0.6
        bicycle:
          min_area: 300
          max_area: 100000
          threshold: 0.6
        bus:
          min_area: 2000
          max_area: 100000
          threshold: 0.6

  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/Living_Room  # Indoor camera uses H.264 main stream
          roles: [detect]  # Add detect role even though detection is disabled
        - path: rtsp://localhost:8554/Living_Room  # Indoor camera uses H.264 main stream
          roles: [record]
    live:
      stream_name: Living_Room_live  # Uses optimized streaming (H.264 direct or transcoded)
    detect:
      enabled: false  # Detection disabled but stream still processed
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true

  Nursery:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/Nursery  # Indoor camera uses H.264 main stream
          roles: [detect]  # Add detect role even though detection is disabled
        - path: rtsp://localhost:8554/Nursery  # Indoor camera uses H.264 main stream
          roles: [record]
    live:
      stream_name: Nursery_live  # Uses optimized streaming (H.264 direct or transcoded)
    detect:
      enabled: false  # Detection disabled but stream still processed
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true

# Global object tracking configuration
objects:
  track:
    - person
    - car
    - truck
    - motorcycle
    - bicycle
    - bus

# Global motion detection settings - more conservative defaults
motion:
  threshold: 25
  contour_area: 15
  delta_alpha: 0.4
  frame_alpha: 0.01
  lightning_threshold: 0.8

# Logging configuration
logger:
  default: info
  logs:
    frigate.mqtt: error
    frigate.app: info

version: 0.15-1
camera_groups:
  test:
    order: 1
    icon: LuBird
    cameras: birdseye
